name: CI/CD

on:
  push:
    branches: ["main", "docker-practice"]
  pull_request:

jobs:
  ci:
    uses: DmitrieugeneGit/devops-ci-pipelines/.github/workflows/go-ci.yml@main
    with:
      go-version: "1.25"
      image-name: tasks-app
      working-directory: backend
      push: false
    secrets: inherit
